name: alpine-linux

on:
  push:
    branches: [ "master", "**" ]
  pull_request:
    branches: [ "master", "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: [3.13.5] #[3.9.3, 3.10.9, 3.11.11, 3.12.7, 3.13.5]

    container: alpine:${{ matrix.tag }}

    steps:
      - run: touch CHANGELOG
      - run: apk add gcc automake autoconf make python3 alpine-sdk libtool ctags gnupg rsync sudo
      - run: python3 -m ensurepip
      - run: ln -sf /usr/bin/python3 /usr/bin/python && ln -sf /usr/bin/pip3 /usr/bin/pip

      - uses: actions/checkout@v2

      - run: |
          git config --global --add safe.directory /__w/nostril/nostril
          make
          make all
          make tags
          sudo make install > /dev/null 2>&1
          type -P nostril && nostril --envelope -t nostril --content ""
